function init(self)
	msg.post("#camera", "acquire_camera_focus")
	msg.post("@render:", "use_camera_projection")
	if sys.get_sys_info().system_name == "Android" then
		go.set("#camera", "orthographic_zoom", 1.3)
	end
end

-- function on_input(self, action_id, action)
-- 	if self.zoom > 0.34 and  action_id == hash("touch")  then
-- 		self.zoom = self.zoom - 0.01
-- 		go.set("#camera", "orthographic_zoom", self.zoom)
-- 	end
-- end
